### ISSUE TITLE
Duration parameter of roller command request

### ISSUE THREAD

**Issue by jghaanstra** [ALLTERCO/ushelly#1]
The GEN1 rest and GEN2 RPC API have an optional duration parameter for the roller open and close command. This is missing in this library. Is it not available in Shelly Cloud Account API or just missing in this example?

If it is missing could it be added for reference.

https://github.com/ALLTERCO/ushelly/blob/73f28585b220f6cac0f719e6b357e61a4569a571/src/devices.ts#L379

**Comment by sdrsdr** [comment]
It was missing from the example. I've verified it exists throughout the cloud code so I'm adding it here as well.
