### ISSUE TITLE
Timeout on WebSocket connection

### ISSUE THREAD

**Issue by SSIvanov19** [ALLTERCO/ushelly#3]
Hi, when I try to run the example, I get the following error:

```
...boot...
restored access token...
devices_new devid: 265292 ( 040c4c ) code: SHPLG-S
...establish_event_link...
reusing access token...
...connection_lost... code: Error: connect ETIMEDOUT <ip address>:6113
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '<ip address>',
  port: 6113
}  reason: undefined
```

It seems that when I try to connect to wss://<shelly_cloud_server>:6113/shelly/wss/hk_sock?t=<ACCESS_TOKEN>, I am getting timeout.

**Comment by sdrsdr** [comment]
Any specific firewall rules at your end? did you retry in some time? Can I have the IP address you try to connect to?  My first impression is that there is some network issue at your end .. while the cloud do have it's hiccups usually it's available for connections or a mob with torches and pitchforks form around our HQ building :)

**Comment by sdrsdr** [comment]
Just checked the instance your device `265292` belongs to it seems properly firewall configured at our end and ETIMEDOUT is not expected anyway:

```
$ telnet shelly-94-eu.shelly.cloud 6113
Trying 35.187.188.31...
Connected to shelly-94-eu.shelly.cloud.
Escape character is '^]'.
dsasd
Connection closed by foreign host.
```
REJECT yes TIMOUT no

**Comment by SSIvanov19** [comment]
Oh, I think the port might be blocked on the internal network. Thanks for helping me.
